package com.nsu.mspagent;

import android.app.*; import android.content.*; import android.net.Uri; import android.os.Bundle; import android.widget.*; import java.io.*; import java.nio.charset.StandardCharsets; import java.util.concurrent.*;
public class DocumentActivity extends Activity {
    private static final int PICK=1001; private Uri uri; private TextView status; private EditText q; private final ExecutorService ex=Executors.newSingleThreadExecutor();
    @Override public void onCreate(Bundle b){super.onCreate(b);LinearLayout p=Ui.page(this,"Document Analysis");p.addView(Ui.text(this,"Select a text-based file (TXT, LOG, JSON, CSV, XML, YAML, PS1, scripts). The Android build sends extracted text to the configured document model. PDF/DOCX/OCR parity is reserved for the next native parser module."));Button pick=Ui.button(this,"Select File");pick.setOnClickListener(v->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("*/*");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,PICK);});p.addView(pick);status=Ui.text(this,"No file selected");p.addView(status);q=Ui.input(this,"Question about this file");p.addView(q);Button run=Ui.button(this,"Analyze");run.setOnClickListener(v->analyze());p.addView(run);setContentView(Ui.scroll(this,p));}
    @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==PICK&&c==RESULT_OK&&d!=null){uri=d.getData();status.setText("Selected: "+uri);}}
    private void analyze(){if(uri==null)return;status.setText("Reading / analyzing...");ex.submit(()->{try{InputStream in=getContentResolver().openInputStream(uri);ByteArrayOutputStream o=new ByteArrayOutputStream();byte[] b=new byte[4096];int n,total=0;while((n=in.read(b))>0&&total<20000){int take=Math.min(n,20000-total);o.write(b,0,take);total+=take;}in.close();String text=o.toString(StandardCharsets.UTF_8.name());AppConfig c=new AppConfig(this);HybridClient hc=new HybridClient(c);String ans=hc.chat("doc","Analyze the supplied MSP/technical document precisely. Do not invent missing content.","DOCUMENT:\n"+text+"\n\nQUESTION:\n"+q.getText().toString());runOnUiThread(()->status.setText("["+hc.lastUsed()+"]\n"+ans));}catch(Exception e){runOnUiThread(()->status.setText("ERROR: "+e.getMessage()));}});}
    @Override protected void onDestroy(){ex.shutdownNow();super.onDestroy();}
}
